{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "faucetbot.serviceAccountName" . }}
  labels:
{{ include "faucetbot.labels" . | nindent 4 }}
{{- end -}}
