services:
  faucet:
    extends:
      file: docker-compose.yml
      service: faucet
    environment:
      SMF_BACKEND_RPC_ENDPOINT: "wss://westend-rpc.polkadot.io/"

      SMF_BOT_MATRIX_BOT_USER_ID: '@westend-faucet:matrix.org'
      SMF_BOT_DRIP_AMOUNT: 1
      SMF_BOT_NETWORK_UNIT: WND
      SMF_BOT_FAUCET_IGNORE_LIST: ''
