chain:
  name: rococo

serviceAccount:
  create: true
  name: rococo

server:
  secret:
    SMF_BACKEND_FAUCET_ACCOUNT_MNEMONIC: from-gitlab-ci-secret-variables
  config:
    SMF_BACKEND_RPC_ENDPOINT: "https://rococo-rpc.polkadot.io/"
    SMF_BACKEND_INJECTED_TYPES: '{}'

bot:
  secret:
    SMF_BOT_MATRIX_ACCESS_TOKEN: from-gitlab-ci-secret-variables
  config:
    SMF_BOT_MATRIX_BOT_USER_ID: '@rococo-faucet-bot:matrix.org'
    SMF_BOT_DRIP_AMOUNT: 100
    SMF_BOT_NETWORK_UNIT: ROC
    SMF_BOT_FAUCET_IGNORE_LIST: ''
