chain:
  name: versi

serviceAccount:
  create: true
  name: versi

server:
  secret:
    # todo secret
    SMF_BACKEND_FAUCET_ACCOUNT_MNEMONIC: from-gitlab-ci-secret-variables
  config:
    SMF_BACKEND_RPC_ENDPOINT: "https://http-versi-rpc-node-0.parity-versi.parity.io"
    SMF_BACKEND_INJECTED_TYPES: '{}'
    SMF_BACKEND_NETWORK_DECIMALS: 12

bot:
  secret:
    SMF_BOT_MATRIX_ACCESS_TOKEN: from-gitlab-ci-secret-variables
  config:
    SMF_BOT_MATRIX_SERVER: 'https://matrix.parity.io'
    SMF_BOT_MATRIX_BOT_USER_ID: '@versi-faucet:matrix.parity.io'
    SMF_BOT_DRIP_AMOUNT: 100
    SMF_BOT_NETWORK_UNIT: VRS
    SMF_BOT_FAUCET_IGNORE_LIST: ''
