substrate-faucet:
  extraLabels:
    team: opstooling
  resources:
    requests:
      memory: 512Mi
      cpu: 0.1
    limits:
      memory: 768Mi
  postgresql:
    primary:
      podLabels:
        team: opstooling
      persistence:
        storageClass: "ssd-csi"
