name: Deploy to DotNS

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: dotns-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-static:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: yarn install --immutable
      - run: yarn run build
        env:
          PUBLIC_CAPTCHA_KEY: 6LcgFI4nAAAAAATrEMoJ6zBacsx5udc1UhGFXemH
          STATIC: "true"
      - uses: actions/upload-artifact@v4
        with:
          name: faucet-dotns
          path: ./client/build
          if-no-files-found: error
          retention-days: 1

  deploy-production:
    if: github.event_name == 'push'
    needs: [build-static]
    uses: paritytech/dotns-sdk/.github/workflows/deploy.yml@main
    with:
      basename: faucet
      artifact-name: faucet-dotns
      mode: production
    secrets:
      dotns-mnemonic: ${{ secrets.DOTNS_MNEMONIC }}

  deploy-preview:
    if: github.event_name == 'pull_request'
    needs: [build-static]
    uses: paritytech/dotns-sdk/.github/workflows/deploy.yml@main
    with:
      basename: faucet
      artifact-name: faucet-dotns
      mode: preview
      subname-format: pr-number
    secrets:
      dotns-mnemonic: ${{ secrets.DOTNS_MNEMONIC }}
