name: Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn generate:papi:e2e
      - run: yarn install --frozen-lockfile
        working-directory: client
      - run: yarn typecheck
      - run: yarn format
      - run: yarn lint
