name: Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4.0.2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Install deps in root
        run: yarn install --frozen-lockfile
      - run: yarn generate:papi:e2e
      - name: Install deps in client
        run: yarn install --frozen-lockfile
        working-directory: client
      - run: yarn typecheck
      - run: yarn format
      - run: yarn lint
